In [1]:
from MoneroAna import *

In [2]:
df = pd.read_csv('../src/overseer.txt', delim_whitespace=True, header=None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,2927514,in,unlocked,2023-07-11,17:08:25Z,0.10000,9c57c572f9f9f5192bd06389d5ea4a166a4c18588f2910...,0,0.000000,83aHpK:0.100000000000,1,-
1,2927523,in,unlocked,2023-07-11,17:27:53Z,85.90000,17aafff5003c91f1f3d33fdab293077d9d839e3d514744...,0,0.000000,83aHpK:85.900000000000,1,-
2,2931910,out,-,2023-07-17,17:56:55Z,0.00000,8c827b848a4bd07c55fe959e4f5389692d9e2625e87ec3...,0,0.000031,-,0,-
3,2931914,out,-,2023-07-17,18:05:28Z,0.00000,3e84234aa990efe2342b3b32cfc186299660c6e9c014b3...,0,0.000031,-,0,-
4,2931919,out,-,2023-07-17,18:16:37Z,0.00000,d7fe2c66925084abfa7afa4c620399fd4c374b386dc35d...,0,0.000031,-,1,-
5,2931927,out,-,2023-07-17,18:35:52Z,0.00000,6b1ca86936d9a924380829a4fc48983413d4b769374b31...,0,0.000031,-,0,-
6,2931928,out,-,2023-07-17,18:40:23Z,0.00000,ee45eddf5fb6bc97b5f9e7ab80ae64850cf78c462fdbb9...,0,0.000031,-,3,-
7,2931944,out,-,2023-07-17,19:02:26Z,0.00000,8126a96f50eac5fabcb0eb0d100c0e639564f689bb746c...,0,0.000086,-,"0,4",-
8,2944703,out,-,2023-08-04,14:31:39Z,1.00000,be869adbc71473428431989d976497e7a4b3f222440ab5...,0,0.000031,-,5,-
9,2944805,out,-,2023-08-04,18:06:34Z,2.00000,5c6be4eac2c548156c49befe2632091680c07cd20722ef...,0,0.000031,-,0,-
10,2944958,out,-,2023-08-04,23:35:56Z,3.00000,f3d856c31fe5ce8d2bc64d17ca83cc7e61db8b8068aec6...,0,0.000044,-,3,-
11,2945027,out,-,2023-08-05,02:04:11Z,4.00000,66895cf13c0cb525fddfbd9b58db92fc5ce733a8fda7d3...,0,0.000031,-,0,-
12,2945295,out,-,2023-08-05,11:44:01Z,0.10000,e6da16f7147a37125aebf6ec36faf9fb0d55473e5f94a0...,0,0.000031,-,0,-
13,2945306,out,-,2023-08-05,12:10:04Z,3.00000,2deb6a7ff79f400340440af51a953de1a194c9af627dc9...,0,0.000031,-,0,-
14,2945306,out,-,2023-08-05,12:10:04Z,2.00000,a98835a38f507bcad90fded2690ac66489f32357c99398...,0,0.000031,-,0,-
15,2945333,out,-,2023-08-05,12:59:59Z,4.00000,a1874949d1aece80a383d790f0d2c06a572057a7da1dc3...,0,0.000031,-,0,-
16,2945387,out,-,2023-08-05,14:30:46Z,5.00000,4f17f31d3abe7b833c448ed6c4d39c0fde102dfdc7bc30...,0,0.000044,-,0,-
17,2976954,in,unlocked,2023-09-18,15:35:42Z,86.06583,e213c6f35ee7164e848f38df0aa0fe5653c33fd95a7e4c...,0,0.000000,83aHpK:86.065830000000,1,-
18,2976955,in,unlocked,2023-09-18,15:38:55Z,47.93417,15f39feccebabc48a88c941bde1992826972c4728ae68c...,0,0.000000,83aHpK:47.934170000000,1,-
19,2977650,out,-,2023-09-19,13:37:18Z,0.10000,5e3b97c2d3a1165fe2a6296f284ba6aeddfe2f1567df46...,0,0.000044,-,0,-
20,2977651,out,-,2023-09-19,13:40:03Z,0.10000,170813eb960bf12cce1cf0ec25ff14b00bced94daf1624...,0,0.000031,-,1,-
21,2977653,out,-,2023-09-19,13:45:08Z,3.10000,424acc1dc2563d513b6723db8ba790e680d1ba4a6d2e98...,0,0.000031,-,1,-
22,2977654,out,-,2023-09-19,13:47:07Z,0.09900,28f66da28108d6aa72c9df052b7ae47ea7068425f6bcb8...,0,0.000031,-,3,-
23,2977676,out,-,2023-09-19,14:25:19Z,2.50000,5cc5acda4597b2a2e217998af6c7fbc11394c9e513dc3e...,0,0.000031,-,0,-

In [4]:
df[0].min(), df[0].max()

(2927514, 2977676)

In [5]:
blocks = [block(i) for i in range(2976900, 2977901)]

In [6]:
%%time
txs = {}
for i in blocks:
    i.get_txs(registry=txs)

CPU times: user 1min 19s, sys: 7.37 s, total: 1min 26s
Wall time: 2min 21s

In [7]:
len(txs)

30167

In [8]:
16*16*16

4096

In [9]:
for i in df[6]:
    print(i, i in txs)

9c57c572f9f9f5192bd06389d5ea4a166a4c18588f2910a255fc3561b3e85b0b False
17aafff5003c91f1f3d33fdab293077d9d839e3d5147442004b4fae592aaab75 False
8c827b848a4bd07c55fe959e4f5389692d9e2625e87ec33a92a49be82c7666a1 False
3e84234aa990efe2342b3b32cfc186299660c6e9c014b38e90962d5f82908e93 False
d7fe2c66925084abfa7afa4c620399fd4c374b386dc35d72713c441a21133a0b False
6b1ca86936d9a924380829a4fc48983413d4b769374b31c29227f982b6b78189 False
ee45eddf5fb6bc97b5f9e7ab80ae64850cf78c462fdbb9ff63c050e1b47f7317 False
8126a96f50eac5fabcb0eb0d100c0e639564f689bb746c2b408632acfb5181b6 False
be869adbc71473428431989d976497e7a4b3f222440ab5e85edca25c5183bb23 False
5c6be4eac2c548156c49befe2632091680c07cd20722ef5ac6c0fc0e31be6dad False
f3d856c31fe5ce8d2bc64d17ca83cc7e61db8b8068aec6b6bb7dc3b44fe64c13 False
66895cf13c0cb525fddfbd9b58db92fc5ce733a8fda7d33a236ddb72697304a1 False
e6da16f7147a37125aebf6ec36faf9fb0d55473e5f94a09175f6541deb15bdbb False
2deb6a7ff79f400340440af51a953de1a194c9af627dc9ced9857a638b1c343e False
a98835a38f507bcad90fded2690ac66489f32357c99398addccd5d5d1d077ede False
a1874949d1aece80a383d790f0d2c06a572057a7da1dc386bc86a72b9c128267 False
4f17f31d3abe7b833c448ed6c4d39c0fde102dfdc7bc30ac76f29a1cab7ae661 False
e213c6f35ee7164e848f38df0aa0fe5653c33fd95a7e4c4c9dafd512a55451ba True
15f39feccebabc48a88c941bde1992826972c4728ae68c4742a2aab5a6a8c95a True
5e3b97c2d3a1165fe2a6296f284ba6aeddfe2f1567df465cb0222a6ee6903abb True
170813eb960bf12cce1cf0ec25ff14b00bced94daf1624e33677e5f4a1a454ef True
424acc1dc2563d513b6723db8ba790e680d1ba4a6d2e98d77a549f403ca0abe5 True
28f66da28108d6aa72c9df052b7ae47ea7068425f6bcb86f8eb6c9fb52a8f69a True
5cc5acda4597b2a2e217998af6c7fbc11394c9e513dc3e696d42229cedc3b40f True

In [10]:
t1 = txs['5e3b97c2d3a1165fe2a6296f284ba6aeddfe2f1567df465cb0222a6ee6903abb']
t2 = txs['170813eb960bf12cce1cf0ec25ff14b00bced94daf1624e33677e5f4a1a454ef']
t3 = txs['a5ad333a2ac7964aa4a095c4042b8d43e95f5244f0b99e78b272088211a70edc']

In [11]:
t1_taint = t1.subtaint(2976950, 310000000, registry=txs)
print(t1_taint)

[<MoneroAna.tx object at 0x7fb231808220>, <MoneroAna.tx object at 0x7fb22f950670>, <MoneroAna.tx object at 0x7fb22eb509a0>, <MoneroAna.tx object at 0x7fb22cf8ef20>, <MoneroAna.tx object at 0x7fb23db73e50>, <MoneroAna.tx object at 0x7fb23cbb5900>, <MoneroAna.tx object at 0x7fb239301510>, <MoneroAna.tx object at 0x7fb22d1525c0>, <MoneroAna.tx object at 0x7fb22ca56050>, <MoneroAna.tx object at 0x7fb22ca554b0>, <MoneroAna.tx object at 0x7fb22c531330>]

In [12]:
t2_taint = t2.subtaint(2976950, 310000000, registry=txs)
print(t2_taint)

[<MoneroAna.tx object at 0x7fb24693e0e0>, <MoneroAna.tx object at 0x7fb241fc2830>, <MoneroAna.tx object at 0x7fb23557f970>, <MoneroAna.tx object at 0x7fb23005c8e0>, <MoneroAna.tx object at 0x7fb22d4fde10>, <MoneroAna.tx object at 0x7fb22cf8f460>, <MoneroAna.tx object at 0x7fb22c87e140>]

In [13]:
t3_taint = t3.subtaint(2976950, 310000000, registry=txs)
print(t3_taint)

[<MoneroAna.tx object at 0x7fb24138a110>, <MoneroAna.tx object at 0x7fb23d276290>, <MoneroAna.tx object at 0x7fb22f0f1b70>, <MoneroAna.tx object at 0x7fb22d4fd180>, <MoneroAna.tx object at 0x7fb22b1da440>, <MoneroAna.tx object at 0x7fb23f22bbe0>, <MoneroAna.tx object at 0x7fb23e5bbfd0>, <MoneroAna.tx object at 0x7fb238a25810>, <MoneroAna.tx object at 0x7fb236739630>, <MoneroAna.tx object at 0x7fb23d4612d0>, <MoneroAna.tx object at 0x7fb234b2fbe0>, <MoneroAna.tx object at 0x7fb230a1f340>, <MoneroAna.tx object at 0x7fb22dce0f40>, <MoneroAna.tx object at 0x7fb22b7c6b00>, <MoneroAna.tx object at 0x7fb22b1d8f40>]

In [14]:
t1_tree = subtaints(t1_taint, 2976950, 310000000, registry=txs)
t2_tree = subtaints(t2_taint, 2976950, 310000000, registry=txs)
t3_tree = subtaints(t3_taint, 2976950, 310000000, registry=txs)

In [15]:
%%time
t1_txs = [next(t1_tree) for i in range(100)]
t2_txs = [next(t2_tree) for i in range(100)]
t3_txs = [next(t3_tree) for i in range(100)]

CPU times: user 14.7 s, sys: 83.5 ms, total: 14.8 s
Wall time: 14.8 s

In [16]:
for i in range(100):
    print(len(t1_txs[i]), len(t2_txs[i]), len(t3_txs[i]))

957 54 145
6897 440 1351
14650 3618 8041
15191 12171 14280
15053 14860 15222
14781 14960 15238
14493 14723 15042
14232 14400 14709
13938 14115 14380
13674 13812 14094
13369 13532 13797
13092 13233 13540
12836 12936 13256
12557 12678 12982
12285 12421 12709
12017 12140 12451
11780 11886 12165
11547 11637 11900
11329 11393 11645
11074 11159 11401
10818 10916 11164
10574 10647 10920
10380 10428 10648
10207 10239 10428
10007 10040 10239
9728 9758 10040
9493 9512 9758
9257 9268 9512
9035 9042 9268
8781 8786 9042
8520 8527 8786
8246 8254 8527
7996 8004 8254
7767 7770 8004
7328 7329 7770
6954 6955 7329
6642 6642 6955
6376 6376 6642
5971 5971 6376
5615 5615 5971
5288 5288 5615
4980 4980 5288
4696 4696 4980
4365 4365 4696
4044 4044 4365
3699 3699 4044
3371 3371 3699
2965 2965 3371
2645 2645 2965
2369 2369 2645
2061 2061 2369
1740 1740 2061
1348 1348 1740
1017 1017 1348
670 670 1017
362 362 670
149 149 362
17 17 149
0 0 17
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0

In [17]:
for i,j,k in zip(t1_txs, t2_txs, t3_txs):
    print(len(i),len(j), len(k), len(list_intersection(i,j)), len(list_intersection(i,k)), len(list_intersection(j,k)))

957 54 145 2 8 3
6897 440 1351 20 61 29
14650 3618 8041 175 713 473
15191 12171 14280 2252 8496 8419
15053 14860 15222 11346 12678 12596
14781 14960 15238 13344 13957 14111
14493 14723 15042 14026 14022 14189
14232 14400 14709 13849 14046 14160
13938 14115 14380 13635 13805 14109
13674 13812 14094 13653 13648 13792
13369 13532 13797 13243 13244 13531
13092 13233 13540 13091 12874 13012
12836 12936 13256 12725 12653 12864
12557 12678 12982 12557 12451 12569
12285 12421 12709 12285 12253 12389
12017 12140 12451 12017 12017 12140
11780 11886 12165 11780 11780 11886
11547 11637 11900 11547 11547 11637
11329 11393 11645 11329 11329 11393
11074 11159 11401 11074 11074 11159
10818 10916 11164 10818 10818 10916
10574 10647 10920 10574 10574 10647
10380 10428 10648 10380 10367 10414
10207 10239 10428 10207 10179 10211
10007 10040 10239 9989 9989 10040
9728 9758 10040 9728 9563 9593
9493 9512 9758 9493 9467 9486
9257 9268 9512 9257 9257 9268
9035 9042 9268 9035 9035 9042
8781 8786 9042 8781 8781 8786
8520 8527 8786 8520 8520 8527
8246 8254 8527 8246 8206 8214
7996 8004 8254 7996 7996 8004
7767 7770 8004 7767 7767 7770
7328 7329 7770 7328 7279 7280
6954 6955 7329 6954 6954 6955
6642 6642 6955 6642 6642 6642
6376 6376 6642 6376 6356 6356
5971 5971 6376 5971 5965 5965
5615 5615 5971 5615 5571 5571
5288 5288 5615 5288 5288 5288
4980 4980 5288 4980 4980 4980
4696 4696 4980 4696 353 353
4365 4365 4696 4365 3218 3218
4044 4044 4365 4044 3806 3806
3699 3699 4044 3699 3546 3546
3371 3371 3699 3371 3234 3234
2965 2965 3371 2965 2939 2939
2645 2645 2965 2645 2608 2608
2369 2369 2645 2369 2363 2363
2061 2061 2369 2061 1989 1989
1740 1740 2061 1740 1683 1683
1348 1348 1740 1348 1348 1348
1017 1017 1348 1017 84 84
670 670 1017 670 644 644
362 362 670 362 329 329
149 149 362 149 23 23
17 17 149 17 11 11
0 0 17 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0